[phases.setup]
nixPkgs = ["php82", "php82Extensions.sqlite3", "php82Extensions.pdo_sqlite"]

[phases.install]
cmds = [
    "composer install --no-dev --optimize-autoloader --no-interaction"
]

[start]
cmd = "bash start.sh"